apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vd57656y7-java-quarkus
  janus-idp.io/tekton: vd57656y7-java-quarkus
  backstage.io/kubernetes-id: vd57656y7-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vd57656y7-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
